### ISSUE TITLE
List view exceeds pixels

### ISSUE THREAD

**Issue by anishre** [anishre/uspeventsapp_v1#12]
@Fazeel-Ali on the nav menu, list view gives an error of overlapping view area by 20 pixels.
I've wrapped the column in "child: SingleChildScrollView()" and reduced profile container height to 60px

Let me know if that's ok. Changes are login portal branch. 

Refer below:
![image](https://user-images.githubusercontent.com/39543074/134268384-0170155c-94de-41cd-80b2-453cc28a064c.png)

**Comment by Fazeel-Ali** [comment]
> @Fazeel-Ali on the nav menu, list view gives an error of overlapping view area by 20 pixels.
> I've wrapped the column in "child: SingleChildScrollView()" and reduced profile container height to 60px
> 
> Let me know if that's ok. Changes are login portal branch.
> 
> Refer below:
> ![image](https://user-images.githubusercontent.com/39543074/134268384-0170155c-94de-41cd-80b2-453cc28a064c.png)

This was because, I was not able to see how it looks and fits in a mobile emulator but the changes looks good and seems okay to me.
